// This file is auto-generated by trix bindgen.

import {
    TRPClient,
    type ArgValue,
    type ClientOptions,
    type SubmitParams,
    type ResolveResponse,
} from "tx3-sdk/trp";


export const DEFAULT_TRP_ENDPOINT = "http://localhost:8164";

export const DEFAULT_HEADERS = {
};

export const DEFAULT_ENV_ARGS = {
};

export type BuyTicketParams = {
    adminTokenName: ArgValue | Uint8Array; // Bytes
    adminTokenPolicy: ArgValue | Uint8Array; // Bytes
    buyer: ArgValue | string; // Address
    ticketName: ArgValue | Uint8Array; // Bytes
    ticketPolicy: ArgValue | Uint8Array; // Bytes
    ticketer: ArgValue | string; // Address
    ticketerScript: ArgValue | string; // UtxoRef
    treasury: ArgValue | string; // Address
}

export const BUY_TICKET_IR = {
    bytecode: "0d03010d010f7469636b657465725f7363726970740702077061796d656e740d02077061796d656e740d01056275796572050e010e010d030c01000005fc002d31010f01050400010000087469636b657465720d02087469636b657465720d01087469636b65746572050c010d011261646d696e5f746f6b656e5f706f6c696379040d011061646d696e5f746f6b656e5f6e616d65040502000000030000030d01087469636b65746572050300020e010e0510020d02087469636b657465720d01087469636b65746572050c010d011261646d696e5f746f6b656e5f706f6c696379040d011061646d696e5f746f6b656e5f6e616d650405020000000005020e0510020d02087469636b657465720d01087469636b65746572050c010d011261646d696e5f746f6b656e5f706f6c696379040d011061646d696e5f746f6b656e5f6e616d650405020000000110010d02087469636b657465720d01087469636b65746572050c010d011261646d696e5f746f6b656e5f706f6c696379040d011061646d696e5f746f6b656e5f6e616d650405020000000d0108747265617375727905000c01000005fc002d31010d0105627579657205000e010e020e0210010d02077061796d656e740d01056275796572050e010e010d030c01000005fc002d31010f0105040001000d030c01000005fc002d31010c010d010d7469636b65745f706f6c696379040d010b7469636b65745f6e616d6504050200010c010d010d7469636b65745f706f6c696379040d010b7469636b65745f6e616d650405020300000000010d020a636f6c6c61746572616c0d01056275796572050d030000010000",
    encoding: "hex",
    version: "v1alpha8",
};

export class Client {
    readonly #client: TRPClient;

    constructor(options: ClientOptions) {
        this.#client = new TRPClient(options);
    }

    async buyTicketTx(args: BuyTicketParams): Promise<ResolveResponse> {
        return await this.#client.resolve({
            tir: BUY_TICKET_IR,
            args,
        });
    }

    async submit(params: SubmitParams): Promise<void> {
        await this.#client.submit(params);
    }
}

// Create a default client instance
export const protocol = new Client({
    endpoint: DEFAULT_TRP_ENDPOINT,
    headers: DEFAULT_HEADERS,
    envArgs: DEFAULT_ENV_ARGS,
});
